# hacks for properly compiling all. Life is not beautiful sometimes

compile: journald_api

journald_api: _build/prod/lib/ejournald/priv/journald_api.so


_build/prod/lib/ejournald/priv/journald_api.so: deps/ejournald/priv/journald_api.so
	mkdir -p $(shell dirname $@ )
	cp $^ $@

deps/ejournald/priv/journald_api.so: deps/ejournald/c_src/journald_api.c
	cd deps/ejournald/c_src/ && make

clean:
	rm -rf deps/ejournald/priv/
	rm -f _build/prod/lib/ejournald/priv/journald_api.so_build/prod/lib/ejournald/priv/journald_api.so
